// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyFolder() {
  return window['go']['main']['App']['ClassifyFolder']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MoveFile(arg1) {
  return window['go']['main']['App']['MoveFile'](arg1);
}

export function Watch() {
  return window['go']['main']['App']['Watch']();
}
